import Head from 'next/head'
import dynamic from 'next/dynamic';
import styles from '../styles/Home.module.css'
import 'mdb-react-ui-kit/dist/css/mdb.min.css';
import { MetaMaskProvider } from 'metamask-react';

const TopHeader = dynamic(() => import('../components/Header'), {
  ssr: false,
})

const Clicker = dynamic(() => import('../components/Click'), {
  ssr: false,
})



export default function Home() {
  return (
    <MetaMaskProvider>
      <div className={styles.container}>
        <TopHeader />
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          {/* <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet" /> */}
          <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
        </Head>

        <main className={styles.main}>
          <Clicker />
        </main>

        <footer className={styles.footer}>
          @copyright 2022
        </footer>
      </div>
    </MetaMaskProvider>
  )
}
